name: tag-demo
on:
  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify git commit sha to build image from'
      deployto:
        type: choice
        description: 'Deploy the built image on environment.'
        options:
          - None
          - Integration
          - Integration and Qa

  # On push to branch
  push:
    branches:
      - master

jobs:
  checkout_build_and_push_docker_image:
    runs-on: ubuntu-latest
    outputs:
      shortsha: ${{ steps.shortsha.outputs.shortsha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Generate git sha(short)
        id: shortsha
        run: echo "shortsha=sha-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Print git sha(short)
        run: echo "The git sha(short) is ${{ steps.shortsha.outputs.shortsha }}"
  run-shell-command:
    runs-on: ubuntu-latest

    if(initial commit) git tag latest steps.shortsha.outputs.shortsha
    steps: 
      - name: multiline script 
        run: |
           git tag -d thirdLatest
          #extract commit id for 2latest
           git rev-parse secondLatest 
           git tag -d secondLatest
          
           git tag thirdLatest steps.shortsha.outputs.shortsha(from46) #create new tag as thirdLatest

           git rev-parse latest #extract commit id for latest
           git tag -d latest
           git tag secondLatest steps.shortsha.outputs.shortsha(from50) #create new tag as 2Latest

           git tag latest master
